### ISSUE TITLE
Meta-package for creating package and handling data from CKAN sources

### ISSUE THREAD

**Issue by coolbutuseless** [ropensci/ozunconf18#30]
The idea is to create a small meta-package that helps with handling data from CKAN sources (like data.gov.au).

e.g. Create a package for the dataset of ASIC business names from https://data.gov.au/dataset/asic-business-names/resource/839cc783-876f-47a2-a70c-0fe606977517

```{r}
create_package(r_package_name = "ASICnames", ckan_source = "data.gov.au", 
datasets = c(ASIC = "839cc783-876f-47a2-a70c-0fe606977517"))
```

This package would:

* Have the user define the CKAN source (e.g. `data.gov.au`) and the `package_id`
* Create a package skeleton for a data-only R package
* Use the meta-info supplied by the data source to populate README.Rmd, description and Roxygen 
* Set up scripts in `data-raw` for pulling the data from the source and creating the data for the package. (Would need some special handlers for different data: csv, zip, shp, kml, json, xml)
* Helper scripts to see if you have the latest data
* Helper scripts for managing multiple versions of the data i.e. keep historical versions for reference.

This would borrow some ideas from [datagovau](https://github.com/ropenscilabs/datagovau)

**Comment by jonocarroll** [comment]
FYI, https://github.com/ropensci/ckanr

If you ask me, I'd prefer to pull the data as required rather than version snapshotting it in a package. Packages to make that easier, such as datagovau and its predecessor could still get some more love.

**Comment by coolbutuseless** [comment]
The problem with pulling data as required is that the data changes over time. 

Some datasets have rolling windows of data availability e.g. "last 5 years of data".

**Comment by Lingtax** [comment]
Definitely worth an in person discussion. Based on last year's ozunconf projects and my subsequent toying with these datasets, the challenge I see is in making these data usable, rather than just accessible. There's usually a lot of junk and un-tidy-ness in these data. 

Admittedly, the ideal solution would be to discourage people from making untidy data in the first place, but lets aim for achievable.

**Comment by coolbutuseless** [comment]
There seems to be distinct phases to a data project

1. Oooh there's data!
2. Grab it by any means necessary.
3. Figure out how to tidy it and make a cool plot.
4. (Never) update it.

Step 3 gets all the love. 

Steps 2+4 are the unsexy drudge work that are done in an ad hoc manner and sometimes not at all.

I'm thinking a package to help manage 2+4 would be beneficial

**Comment by coolbutuseless** [comment]
Why I haven't heard about bowerbird before! https://github.com/ropensci/bowerbird

Looks great!

I think my metackanr idea is now redundant...

**Comment by raymondben** [comment]
Hmm, don't know about "redundant". Bowerbird might be a good base upon which to build, but by itself it doesn't do everything you describe in the proposed metackanr scope. Happy to chat about it though ....
FWIW there's a bowerbird example of retrieving a data.gov.au data set [here](https://github.com/ropensci/bowerbird/blob/master/R/get.R#L31).
